In [1]:
import pandas as pd
import numpy as np

In [3]:
catmap = pd.read_csv('map1.csv')
article = pd.read_csv('articles.csv')

In [4]:
article

,latest_update_time,language,author_name,article_category,article_id,timestamp,article_sub_category,trending
0,2019-04-08 18:27:20.636345+00:00,1,Aparna Ganesan,3.0,4179,2019-04-08 13:50:12.767183+00:00,16.0,True
1,2019-04-08 17:49:41.555242+00:00,1,Ashish Yechury,3.0,4176,2019-04-08 13:34:34.977878+00:00,57.0,True
2,2019-04-08 17:49:41.555242+00:00,1,Ashish Yechury,3.0,4176,2019-04-08 13:34:34.977878+00:00,372.0,True
3,2019-04-08 17:31:40.703664+00:00,4,പൊളിറ്റിക്കൽ ഡെസ്ക്,42.0,4185,2019-04-08 15:25:08.926918+00:00,97.0,True
4,2019-04-08 17:31:40.703664+00:00,4,പൊളിറ്റിക്കൽ ഡെസ്ക്,134.0,4185,2019-04-08 15:25:08.926918+00:00,97.0,True
5,2019-04-08 17:31:40.703664+00:00,4,പൊളിറ്റിക്കൽ ഡെസ്ക്,135.0,4185,2019-04-08 15:25:08.926918+00:00,97.0,True
6,2019-04-08 16:49:08.194626+00:00,4,പൊളിറ്റിക്കൽ ഡെസ്ക്,135.0,4184,2019-04-08 15:05:26.038463+00:00,97.0,True
7,2019-04-08 16:08:08.984822+00:00,4,അഫീഫ,81.0,4181,2019-04-08 14:15:31.826024+00:00,146.0,True
8,2019-04-08 16:06:28.432556+00:00,4,"പാര്‍വ്വതി, ഷിബില്‍ വി.എം.",42.0,4186,2019-04-08 16:06:26.447581+00:00,185.0,False
9,2019-04-08 16:06:28.432556+00:00,4,"പാര്‍വ്വതി, ഷിബില്‍ വി.എം.",110.0,4186,2019-04-08 16:06:26.447581+00:00,185.0,False
10,2019-04-08 14:49:46.918788+00:00,1,Supriyo Mukherjee and Andrew Lu,6.0,4183,2019-04-08 14:49:44.843687+00:00,26.0,True
11,2019-04-08 14:23:51.299633+00:00,2,एशियाविल डेस्क,126.0,4182,2019-04-08 14:23:49.244044+00:00,354.0,True
12,2019-04-08 14:12:29.962916+00:00,3,ஜோ கார்த்திக்,39.0,4177,2019-04-08 13:31:08.573397+00:00,90.0,True
13,2019-04-08 14:00:17.575817+00:00,2,एशियाविल डेस्क,46.0,4180,2019-04-08 13:58:20.777160+00:00,118.0,True
14,2019-04-08 13:55:41.433935+00:00,3,ஏசியாவில் செய்திப் பிரிவு,128.0,4167,2019-04-08 13:55:11.624139+00:00,323.0,True
15,2019-04-08 13:45:48.220155+00:00,3,ஏசியாவில் செய்திப் பிரிவு,128.0,4178,2019-04-08 13:45:46.180940+00:00,323.0,True
16,2019-04-08 13:09:22.380002+00:00,4,പൊളിറ്റിക്കല്‍ ഡെസ്ക്,42.0,4168,2019-04-08 11:49:37.975734+00:00,97.0,True
17,2019-04-08 13:00:10.805155+00:00,4,സ്പോർട്സ് ഡെസ്ക്,116.0,4175,2019-04-08 12:54:29.689723+00:00,256.0,True
18,2019-04-08 12:42:24.804955+00:00,1,Athira Madhav,136.0,4155,2019-04-08 12:42:22.780509+00:00,57.0,False
19,2019-04-08 12:39:01.899130+00:00,1,Asiaville Desk,99.0,4174,2019-04-08 12:34:28.765091+00:00,192.0,False
20,2019-04-08 12:19:50.352355+00:00,2,एशियाविल डेस्क,103.0,4173,2019-04-08 12:19:48.409974+00:00,197.0,True
21,2019-04-08 12:18:58.320241+00:00,1,Supriyo Mukherjee,6.0,4141,2019-04-08 12:18:56.329953+00:00,12.0,True
22,2019-04-08 12:18:32.613863+00:00,1,Mayank Mohanti,14.0,4172,2019-04-08 12:18:30.920803+00:00,305.0,True
23,2019-04-08 12:16:20.558639+00:00,2,एशियाविल डेस्क,126.0,4148,2019-04-08 07:58:09.907926+00:00,353.0,True
24,2019-04-08 12:15:28.437258+00:00,2,एशियाविल डेस्क,126.0,4171,2019-04-08 12:15:26.501417+00:00,354.0,True
25,2019-04-08 12:15:14.962232+00:00,2,एशियाविल डेस्क,126.0,4170,2019-04-08 12:14:40.265476+00:00,354.0,True
26,2019-04-08 11:11:06.058097+00:00,1,Athulya Nambiar,6.0,4164,2019-04-08 11:11:03.970979+00:00,12.0,False
27,2019-04-08 11:11:06.058097+00:00,1,Athulya Nambiar,6.0,4164,2019-04-08 11:11:03.970979+00:00,322.0,False
28,2019-04-08 11:09:49.173236+00:00,2,एशियाविल डेस्क,126.0,4157,2019-04-08 09:24:13.101199+00:00,354.0,True
29,2019-04-08 11:08:02.259653+00:00,2,श्याम सुंदर,69.0,4166,2019-04-08 10:42:04.608229+00:00,139.0,True
...,...,...,...,...,...,...,...,...
6371,2019-01-10 11:29:23.865335+00:00,1,Ashutosh,5.0,29,2018-06-20 06:57:19.079469+00:00,4.0,False
6372,2019-01-10 11:28:49.890221+00:00,1,Ashutosh,12.0,21,2018-06-20 05:21:03.202991+00:00,5.0,False
6373,2018-12-30 22:26:31.443214+00:00,1,Greg McFarlane,13.0,144,2018-07-27 07:33:23.257997+00:00,9.0,False
6374,2018-12-28 09:29:24.669679+00:00,1,Greg McFarlane,13.0,143,2018-07-27 07:30:04.857966+00:00,9.0,False
6375,2018-12-28 09:29:14.838786+00:00,1,Testing,13.0,161,2018-08-01 11:37:32.586676+00:00,27.0,True
6376,2018-12-28 09:29:12.431850+00:00,1,Raaj,4.0,36,2018-06-20 09:00:47.829800+00:00,7.0,False
6377,2018-12-28 09:29:11.801622+00:00,1,PTI,13.0,42,2018-06-20 09:38:35.117712+00:00,9.0,False
6378,2018-12-28 09:29:09.390141+00:00,1,Raaj,14.0,28,2018-06-20 06:51:51.659771+00:00,13.0,False
6379,2018-12-28 09:29:08.172661+00:00,1,Raaj,4.0,45,2018-06-20 10:21:36.901245+00:00,6.0,False
6380,2018-12-28 09:29:06.941643+00:00,1,Raaj,4.0,41,2018-06-20 09:37:30.145126+00:00,6.0,False
6381,2018-12-28 09:29:05.758908+00:00,1,Arul Aneja,13.0,49,2018-06-21 08:32:26.618489+00:00,9.0,False
6382,2018-12-28 09:28:56.722944+00:00,1,jeniffa,13.0,65,2018-07-03 14:43:20.396800+00:00,22.0,False
6383,2018-12-28 09:28:47.607516+00:00,1,jeniffa,13.0,72,2018-07-04 14:29:04.038150+00:00,9.0,False
6384,2018-12-28 09:28:46.391304+00:00,1,jeniffa,12.0,74,2018-07-04 14:46:43.395512+00:00,14.0,False
6385,2018-12-28 09:28:45.199059+00:00,1,jeniffa,4.0,77,2018-07-04 15:11:01.202553+00:00,21.0,False
6386,2018-12-28 09:28:45.199059+00:00,1,jeniffa,4.0,77,2018-07-04 15:11:01.202553+00:00,25.0,False
6387,2018-12-28 09:28:43.982994+00:00,1,jeniffa,14.0,78,2018-07-04 15:16:46.288135+00:00,13.0,False
6388,2018-12-28 09:28:42.798810+00:00,1,jeniffa,14.0,70,2018-07-04 14:06:12.826556+00:00,13.0,False
6389,2018-12-28 09:28:39.212439+00:00,1,jeniffa,13.0,81,2018-07-05 13:36:09.547611+00:00,27.0,True
6390,2018-12-28 09:28:38.036589+00:00,1,jeniffa,10.0,76,2018-07-04 15:02:51.143211+00:00,24.0,False
6391,2018-12-28 09:28:37.442687+00:00,1,jeniffa,14.0,87,2018-07-05 14:41:05.191922+00:00,30.0,False
6392,2018-12-28 09:28:36.858155+00:00,1,jeniffa,12.0,85,2018-07-05 14:26:50.845932+00:00,29.0,False
6393,2018-12-28 09:28:35.648343+00:00,1,jeniffa,11.0,84,2018-07-05 14:18:12.098249+00:00,28.0,False
6394,2018-12-28 09:28:34.488272+00:00,1,jeniffa,11.0,90,2018-07-05 15:02:59.637067+00:00,31.0,False
6395,2018-12-28 09:28:33.880396+00:00,1,jeniffa,5.0,89,2018-07-05 14:56:10.677496+00:00,26.0,True
6396,2018-12-28 09:28:33.277403+00:00,1,jeniffa,10.0,91,2018-07-05 15:30:43.715038+00:00,24.0,True
6397,2018-12-28 09:28:32.108075+00:00,1,jeniffa,14.0,94,2018-07-06 14:12:27.832517+00:00,13.0,True
6398,2018-12-28 09:28:30.907644+00:00,1,jeniffa,10.0,98,2018-07-06 14:49:08.785752+00:00,24.0,False
6399,2018-12-28 09:28:29.118487+00:00,1,Boolmberg,13.0,104,2018-07-06 15:20:16.078640+00:00,8.0,True
6400,2018-12-28 09:28:29.118487+00:00,1,Boolmberg,13.0,104,2018-07-06 15:20:16.078640+00:00,9.0,True

In [52]:
feat = pd.DataFrame()

for i in article['article_id'].unique():
    t1 = 0
    t2 = 0
    t3 = 0
    t4 = 0
    t5 = 0
    t6 = 0
    t7 = 0
    t8 = 0
    t9 = 0
    t10 = 0
    t11 = 0
    t12 = 0
    t13 = 0
    t14 = 0
    t15 = 0
    t16 = 0
    for j in range(article.shape[0]):
        if article['article_id'].iloc[j] == i:
            k1 = article['language'].iloc[j]
            k2 = article['trending'].iloc[j]*1
            if len(catmap['mapping'].loc[catmap['id'] == article['article_category'].iloc[j]]) >0:
                k3 = catmap['mapping'].loc[catmap['id'] == article['article_category'].iloc[j]].values.tolist()[0]

                if k3 == 1: 
                    t1 +=1
                if k3 == 2: 
                    t2 +=1
                if k3 == 3: 
                    t3 +=1
                if k3 == 4: 
                    t4 +=1
                if k3 == 5: 
                    t5 +=1
                if k3 == 6: 
                    t6 +=1
                if k3 == 7: 
                    t7 +=1
                if k3 == 8: 
                    t8 +=1
                if k3 == 9: 
                    t9 +=1
                if k3 == 10: 
                    t10 +=1
                if k3 == 11: 
                    t11 +=1
                if k3 == 12: 
                    t12 +=1
                if k3 == 13: 
                    t13 +=1
                if k3 == 14: 
                    t14 +=1
                if k3 == 15: 
                    t15 +=1
                    t16 +=1
    data = pd.DataFrame(np.column_stack([i,k1,k2,t1 ,	t2 ,	t3 ,	t4 ,	t5 ,	t6 ,	t7 ,	t8 ,	t9 ,	t10 ,	t11 ,	t12 ,	t13 ,	t14 ,	t15 ,	t16 ,
    ]), columns=['articleid','language','trending',  'Politics ',	 'Environment ',	 'Arts & Culture ',	 'Sports ',	 'economy ',	 'buisness tamil ',	 'media ',	 'health ',	 'fassion ',	 'election ',	 'misc. ',	 'most popular ',	 'technology ',	 'education ',	 'voice / video ',	 'interactive/live '])
    feat = feat.append(data, ignore_index=True)                if k3 == 16: 


feat.head(5)

,articleid,language,trending,Politics,Environment,Arts & Culture,Sports,economy,buisness tamil,media,health,fassion,election,misc.,most popular,technology,education,voice / video,interactive/live
0,4179,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,4176,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,4185,4,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1
3,4184,4,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
4,4181,4,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [61]:
feat.to_csv('features.csv')

In [50]:
k = pd.DataFrame(article['article_category'].unique())
k.to_csv('2.csv')